etc_hosts: [
  { host_ip: "10.10.0.10", host_name: "admin"},
  { host_ip: "10.10.0.11", host_name: "manager1"},
  { host_ip: "10.10.0.12", host_name: "manager2"},
  { host_ip: "10.10.0.21", host_name: "worker"},
]

