- name: install docker compose
  get_url:
      url: https://github.com/docker/compose/releases/download/1.14.0-rc2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
  tags: [docker-compose]
